[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python", "node"]
trusted_config_paths = [
    "~/workspace",
    "~/dev",
    "~/code",
    "~/work"
]

[tools]
python = "3.13.11"
node = "lts"
rust = "stable"
uv = "latest"
